<?php require 'includes/header.php';?>
  <main class="mt-24 px-5 container mx-auto leading-8">
    <div>
      <h1 class="text-xl font-bold">Our Mission</h1>
      <p class="mt-5 sm:mx-16">Privacy has become a heated topic over the past few years and consumers have become much more aware of the growing issues with large companies.  Personal information and other data are being mass collected for the purpose of "Relevant Advertisements" and suggested content. Consumers that don't like this sort of collection have been trying to hide their habits and switch to alternatives. As these consumers work on a more private life, some have realized the difficulty of moving away certain services like YouTube.  Alternatives exist, however these alternatives lack the content that these consumers have become used to. Many will still use YouTube despite the privacy risks that it may have. FreeTube's mission is to help as many people in this group as we can. Our goal is to allow users to watch YouTube in a familiar and user friendly way while minimizing the privacy violations that come from using YouTube.</p>
    </div>
    <div class="mt-24">
      <h1 class="text-xl font-bold">How It All Started</h1>
      <p class="mt-5 sm:mx-16">I started FreeTube as a passion project. My time digging into the rabbit hole of privacy has changed the way I use things a lot. I became more aware at how I was being tracked and for what reasons. Things like YouTube became an invaluable source of both entertainment and knowledge that I and quite a few others were not ready to give up.</p>
      <p class="mt-5 sm:mx-16">The tracking became too much for me when I was being introduced to a show on Netflix. It was relatively new at the time but I haven't heard of it yet.  A friend came over to my house to log in to his Netflix account on my TV (as I don't have a Netflix account) and we watched a few episodes. A couple of days pass and my YouTube suggestions are now flooded with recommendations for this show that I haven't heard of until recently. The only connection between my YouTube account and my "interest" in this show was my friend's Netflix account that happened to be on the same network watching it.</p>
      <p class="mt-5 sm:mx-16">Now, maybe I was reaching too far to make the connection, but it was too strange to me to think otherwise. I started thinking of ways to prevent this from happening again. HookTube was alive and doing well at the time which helped. The lack of any subscription support made it difficult to use as an ideal alternative though. I waited a while with the idea of "someone else will probably make what I want" (Looking back, Invidious did come out shortly after FreeTube so I was kinda right in that regards). I never found the solution that I wanted so I got to work on FreeTube and now we're here.</p>
    </div>
  </main>
<?php require 'includes/footer.php';?>
