<?php require 'includes/header.php';?>
  <main class="mt-24 px-5 container mx-auto leading-8">
    <div>
      <h1 class="text-xl font-bold">Our Mission</h1>
      <p class="mt-5 sm:mx-16">Privacy is something that has become more important as the years go by.  Every day something new is being created to take advantage of you and your data.  Many of those that are aware of these violations feel helpless and eventually accept the new normal.  These same people might even be aware that alternatives exist however they find difficulty switching due to one reason or another.  YouTube has become one such platform where those that use it still enjoy the service however they're not pleased with the misuse of their information when using the platform.  Alternatives that are out there won't have the same content creators as the ones you are used to.  With FreeTube, our mission is to provide a happy medium for these people where they can use YouTube on their own terms.  We aim to show those that struggle with privacy that privacy can be easy and achievable.  We want FreeTube to be accesible to all types of users by being as user-friendly and as feature-rich as possible while also maintaining as much privacy as possible while using YouTube.</p>
    </div>
    <div class="mt-24">
      <h1 class="text-xl font-bold">History of FreeTube</h1>
      <p class="mt-5 sm:mx-16">FreeTube was started in late December of 2017 as a personal desire.  I started to have a grown interest in privacy and was in the transitional process of getting rid of some of the apps that I used daily that ended up becoming too invasive for me.  YouTube was one of those apps that I wanted to get rid of, but at the time it wasn't very feasible.</p>
      <p class="mt-5 sm:mx-16">It was later on that I realized that YouTube is tracking more than what I was comfortable with.  My recommendations feed were suspiciously filled with videos of things that I've never searched for on YouTube.  In one case, they were about things that I never even searched for on the same machine.  It was too strange to not feel like a coincidence and I really didn't like it.  I decided I wanted to do something about it, so I started to look for solutions.</p>
      <p class="mt-5 sm:mx-16">Around this time, there was already a well-known solution, HookTube.  HookTube was a way to watch YouTube privately, though it was very basic for my needs.  It didn't have common features like subscriptions or a way to save videos in an capacity.  I decided that I could probably make a similar application while also having the features that I wanted.  I hesitated on this thought though as I wasn't too confident in myself.  I figured surely someone else would also put something like this together and it'd probably be better than whatever I could do (turns out I was right about this, because Invidious was released a few months after FreeTube did).  Eventually, I decided to work on it anyways.</p>
      <p class="mt-5 sm:mx-16">In March of 2018, I relelased the first iteration of FreeTube.  I had spent quite a bit of time on it at this point and I figured that others on the internet might be interested in what I was putting together.  It was pretty rough around the edges, but it was usable.  It was mostly on par with HookTube as far as features go along with having subscriptions, so some people found some use in it.</p>
      <p class="mt-5 sm:mx-16">A couple of months later, HookTube got into some legal trouble with YouTube over their use of the YouTube API and was forced to essentially stop development.  This made me unsure of what to do with FreeTube.  Around this time though, Invidious became released to the public.  It was similar to HookTube, but it also had account support to store subscriptions.  Most importantly though, it had it's own API that scraped YouTube.  I worked with the developer of Invidious to switch FreeTube over to this new API.  After a while, the transition became a success of FreeTube was able to continue development without much worry.  This happily continued for about a year or so.</p>
      <p class="mt-5 sm:mx-16">Eventually, I became displeased with the current code base of FreeTube.  The code has now become a mess to maintain and even harder to fix some of the bugs associated with it.  Some new features became difficult to implement just because of how poorly it was put together.  I've been able to learn a lot as a developer at this point however FreeTube now no longer reflected what I could do.  I eventually became frustrated with myself and wanted to start over.</p>
      <p class="mt-5 sm:mx-16">In early 2020, I decided to scrap the years of development that I've done and started rewriting FreeTube.  This became a fresh new base with brand new coding standards that are much more in line with what I could do in present day.  Progress was moving slowly however it was clear that this new version of FreeTube was going to be much more stable as time went on.  I was even able to add new features along the way that would have never been possible in the old code base, such as a fully local API and full app navigation support.</p>
      <p class="mt-5 sm:mx-16">About half way through 2020, it was announced that the lead developer of Invidious was going to step down from Invidious to work on other things.  Invidious was still an important piece of the rewrite however my work towards a local API made me more prepared for this announcement than I would have been otherwise.  While it was sad to see that development of Invidious was going to slow down by a lot, it gave me the notice that I needed to speed up my work on the rewrite</p>
      <p class="mt-5 sm:mx-16">Soon after, the community started to step in and help out.  We wanted to get everything done before the Invidious API on the main instance shuts down, so that the community can still have a reliable method of privately watching YouTube.  Progress skyrocketed at this time and we were able to get many things done quickly.</p>
      <p class="mt-5 sm:mx-16">In October of 2020, I was finally able to deliver on what I initially set out to do.  FreeTube has been rewritten and was better than ever.  I now continue the development of FreeTube to this day knowing that everything is much cleaner than before.  Hopefully we're in a state where I don't have to do this again.</p>
    </div>
  </main>
<?php require 'includes/footer.php';?>
