name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sshAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote and Pull Changes
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: 22
        script: |
          cd /var/www/FreeTubeApp.io
          git pull
