# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sshAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote and Pull Changes
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: 22
        script: |
          cd /var/www/FreeTubeApp.io
          git pull
